### ISSUE TITLE
example code logic / error

### ISSUE THREAD

**Issue by thegodone** [Qiong-Yang/FastEI#5]
I've testing the code and basically I have this output of the query molecules but the answer is quite strange : 

here the smiles in the test folder
![image](https://github.com/Qiong-Yang/FastEI/assets/1186658/45c30d02-415e-4404-b12a-4173c8ece273)

here the answer based on the indexes found :
![image](https://github.com/Qiong-Yang/FastEI/assets/1186658/2bd26356-9363-47cd-9e9a-e4bfd14bebe7)

and If I look at only the first molecule (ie I[0]): 
<img width="182" alt="image" src="https://github.com/Qiong-Yang/FastEI/assets/1186658/3f7bae5f-95ba-4e1c-ae5f-33be03d0d905">

I don't see any accurate matching at all, can you tell me what can be the issue ?
here the matching index I have [2117858, 83971, 1358966, 1944009, 46292, 213015, 901693, 253884, 173348, 1360939]
```
matching_index=[I[0][0],I[1][0],I[2][0],I[3][0],I[4][0],I[5][1],I[6][8],I[7][14],I[8][17],I[9][99]]
print(matching_index)
```

**Comment by Qiong-Yang** [comment]
Because of some directory and file naming changes, I update example.py with the data from https://doi.org/10.5281/zenodo.7907140. You can firstly download the relevant data
(Word2vec.model, HNSW_index.bin, The expanded in-silico library.db) from https://doi.org/10.5281/zenodo.7907140, and put them to the data directory (data/Word2vec.model, HNSW_index.bin, The expanded in-silico library.db), and then run the code (example.py).

**Comment by Qiong-Yang** [comment]
![example_run](https://github.com/Qiong-Yang/FastEI/assets/46306770/d29dcba3-56a4-49b4-af83-bd9a1be79a87)

**Comment by thegodone** [comment]
I see the error now, it was this line model_file ="../model/references_word2vec.model" by replacing by data/... it works now.

Thank you
